import React from 'react';
import { X, Shield, BookOpen, AlertTriangle, CheckCircle2 } from 'lucide-react';

export const TermsModal = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 md:p-8">
      <div className="bg-white rounded-2xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between p-6 border-b border-slate-100 bg-slate-50">
          <div className="flex items-center gap-3 text-white">
            <Shield className="text-brand-blue" size={24} />
            <h2 className="text-xl font-bold">Terms of Service & Privacy Policy</h2>
          </div>
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-300 hover:bg-white/10 rounded-full transition-colors">
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6 flex-1 overflow-y-auto prose prose-sm prose-slate max-w-none">
          <h3>1. Nature of the Service (Not Legal Advice)</h3>
          <div className="bg-red-50 border border-red-100 p-4 rounded-xl text-red-900 mb-6">
            <p className="font-bold flex items-center gap-2 m-0"><AlertTriangle size={16} /> IMPORTANT DISCLAIMER</p>
            <p className="text-xs mt-2 mb-0">REM-Leases provides document analysis software utilizing artificial intelligence. <strong>REM-Leases does not provide legal advice, legal opinions, or legal services.</strong> The output generated by REM-Leases is for informational and research purposes only and must never substitute the professional judgment of a qualified attorney. The User bears sole professional and ethical responsibility for verifying all outputs, deadlines, citations, and statutory interpretations generated by the software before relying on them in any legal proceeding, contract, or client advice. REM-Leases assumes no liability whatsoever for errors, omissions, or AI "hallucinations".</p>
          </div>
          
          <h3>2. AI Limitations & Hallucinations</h3>
          <p>While REM-Leases is engineered with strict prompting to minimize inaccuracies, Large Language Models (LLMs) can "hallucinate" or generate plausible-sounding but completely fabricated information. Users must:</p>
          <ul>
            <li>Always click the citation badges (e.g., <code>[Filename, Page X]</code>) to verify the original text in the source document.</li>
            <li>Treat any generative output without a specific, verifiable citation as highly suspect or invalid.</li>
          </ul>

          <h3>3. Data Privacy & Confidentiality</h3>
          <p>We understand that legal professionals are bound by strict attorney-client privilege. Our architecture is designed with absolute confidentiality as the primary objective:</p>
          <ul>
            <li><strong>Zero-Retention Inference:</strong> We utilize enterprise API agreements with our LLM providers (e.g., Groq) which explicitly guarantee that your uploaded documents and prompts are <strong>not used to train foundational AI models</strong> and are permanently deleted immediately after inference.</li>
            <li><strong>Vector Storage Security:</strong> Document embeddings are stored securely in isolated namespaces within our Pinecone database, encrypted at rest and in transit.</li>
            <li><strong>Automated Purging:</strong> To minimize data liability, you may delete your Workspaces at any time, which permanently shreds the associated vector data from our servers.</li>
          </ul>

          <h3>4. Indemnification</h3>
          <p>The User agrees to indemnify, defend, and hold harmless REM-Leases, its officers, directors, employees, and agents, from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with the User's access to or use of the Service or the User's violation of these Terms.</p>
        </div>
        <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end">
          <button onClick={onClose} className="px-6 py-2 bg-brand-blue text-white rounded-lg font-bold hover:bg-brand-accent transition-colors shadow-sm">I Understand & Agree</button>
        </div>
      </div>
    </div>
  );
};

export const HowToModal = ({ onClose }) => {
  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 md:p-8">
      <div className="bg-white rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in duration-200">
        <div className="flex items-center justify-between p-6 border-b border-slate-100 bg-slate-50">
          <div className="flex items-center gap-3 text-white">
            <BookOpen className="text-brand-accent" size={24} />
            <h2 className="text-xl font-bold">How to Use REM-Leases: Best Practices</h2>
          </div>
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-300 hover:bg-white/10 rounded-full transition-colors">
            <X size={20} />
          </button>
        </div>
        
        <div className="p-6 flex-1 overflow-y-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            <div className="space-y-6">
              <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                <h3 className="font-bold text-brand-blue flex items-center gap-2 text-base mb-3"><CheckCircle2 size={18}/> 1. Build Your Case File</h3>
                <p className="text-sm text-slate-300 leading-relaxed">Create a <strong>Workspace</strong> for a specific client or matter and upload the relevant PDFs (pleadings, contracts, dockets). REM-Leases reads <em>all</em> documents in a workspace simultaneously when you ask a question. Grouping related files yields the smartest cross-document insights.</p>
              </div>

              <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                <h3 className="font-bold text-brand-blue flex items-center gap-2 text-base mb-3"><CheckCircle2 size={18}/> 2. The Golden Rule: Verify Citations</h3>
                <p className="text-sm text-slate-300 leading-relaxed">REM-Leases is programmed to strictly append a citation (like <code>[contract.pdf, Page 4]</code>) to every statement of fact. If a statement lacks a citation, or you want to be 100% sure, click your document in the sidebar to manually verify the context. <strong>Never blindly submit AI output to a court.</strong></p>
              </div>
            </div>

            <div className="space-y-6">
              <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                <h3 className="font-bold text-brand-blue flex items-center gap-2 text-base mb-3"><CheckCircle2 size={18}/> 3. Use the Regional Knowledge Base</h3>
                <p className="text-sm text-slate-300 leading-relaxed">Working in South Africa? Toggle on the <strong>Premium SA Knowledge Base</strong> in the sidebar. When active, REM-Leases will automatically cross-reference your uploaded private facts against the SA Constitution, Uniform Rules, Companies Act, NCA, LRA, and BCEA to catch procedural or regulatory violations.</p>
              </div>

              <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl">
                <h3 className="font-bold text-brand-blue flex items-center gap-2 text-base mb-3"><CheckCircle2 size={18}/> 4. Draft Automation (Export to Word)</h3>
                <p className="text-sm text-slate-300 leading-relaxed">Found the perfect argument or generated a flawless Chronological Timeline? Click the small <strong>Download to Word</strong> icon below the AI's response to instantly export the text as a natively formatted <code>.docx</code> file, ready for you to paste into your firm's letterhead templates.</p>
              </div>
            </div>

          </div>

          <div className="mt-8 bg-blue-50/50 border border-blue-100 p-5 rounded-xl">
             <h3 className="font-bold text-white mb-2">💡 Prompting Pro-Tips for Lawyers</h3>
             <ul className="text-sm text-slate-300 space-y-2 list-disc pl-5 marker:text-brand-blue">
                 <li><strong>Be specific:</strong> Instead of "Summarize this," ask "Summarize the plaintiff's arguments regarding the alleged breach of Clause 4, and list any mentioned dates."</li>
                 <li><strong>Ask for contradictions:</strong> "Identify any conflicting statements between the witness affidavit and the police docket regarding the time of the incident."</li>
                 <li><strong>Procedural checks:</strong> "Based on the date of service on page 1 of this Notice of Motion, calculate the deadline to file a Notice to Oppose under the Uniform Rules of Court." (Requires SA Knowledge Base to be active).</li>
             </ul>
          </div>

        </div>
        <div className="p-6 border-t border-slate-100 bg-slate-50 flex justify-end">
          <button onClick={onClose} className="px-6 py-2 bg-slate-800 text-white rounded-lg font-bold hover:bg-slate-900 transition-colors shadow-sm">Got it, let's work</button>
        </div>
      </div>
    </div>
  );
};
